### ISSUE TITLE
Добавление прогноза

### ISSUE THREAD

**Issue by soulthiefer** [IATkachenko/HA-YandexWeather#10]
добрый день  !
установил , погоду на сегодня показывает а вот прогноз на дни вперед никакой информации 
![image](https://user-images.githubusercontent.com/78509632/152577186-0c90096c-9335-4389-a99d-19868f838b0f.png)

в чем проблема ?

**Comment by IATkachenko** [comment]
Прогноз пока интеграцией не поддерживается. Но я копаю в этом направлении.

Ну и да понимания: Яндекс отадет прогноз только на два следующих временных интевала: вечером на ночь и утро.
