### ISSUE TITLE
У Яндекса больше нет бесплатного тарифа "погода для сайта"

### ISSUE THREAD

**Issue by shatz07** [IATkachenko/HA-YandexWeather#104]
### В чем проблема?

Как я понимаю, в текущей версии API убрали тариф "погода для сайта", теперь бесплатных тарифов не осталось. Следовательно, новые пользователи не смогут настроить интеграцию.
https://yandex.ru/dev/weather/doc/ru/concepts/pricing

**Comment by IATkachenko** [comment]
Шик, блеск, талантливые маркетологи.

**Comment by visteras** [comment]
А старые тарифы, если успел начать пользоваться, действовать продолжают?

**Comment by IATkachenko** [comment]
> А старые тарифы, если успел начать пользоваться, действовать продолжают?
Архивный тариф, должно работать -- https://yandex.ru/dev/weather/doc/ru/concepts/pricing#info

**Comment by EvgenyBash** [comment]
Добрый день!

Вот эта ошибка не из-за блокировки Яндексом?

`Регистратор: homeassistant.util.loop
Источник: util/loop.py:84
Первое сообщение: 10:53:11 (5 сообщений)
Последнее сообщение: 12:53:11

Detected blocking call to open inside the event loop by custom integration 'yandex_weather' at custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f: (offender: /config/custom_components/yandex_weather/updater.py, line 137: with open(_translation_location) as f:), please create a bug report at https://github.com/IATkachenko/HA-YandexWeather/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval await self._async_refresh(log_failures=True, scheduled=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/yandex_weather/updater.py", line 260, in update self.process_data(result, r["fact"], CURRENT_WEATHER_ATTRIBUTE_TRANSLATION) File "/config/custom_components/yandex_weather/updater.py", line 211, in process_data value = translate_condition( File "/config/custom_components/yandex_weather/updater.py", line 137, in translate_condition with open(_translation_location) as f:`

**Comment by IATkachenko** [comment]
Доброго дня, 

нет, интеграция до файликов добраться не может. Откройте новое issue, пожалуйста: там посмотрим что к чему, чтобы в кучу не валилось все.

**Comment by dmitkam** [comment]
Бесплатное API ?
https://yandex.ru/pogoda/b2b/smarthome

**Comment by rozhkovets** [comment]
> Бесплатное API ? https://yandex.ru/pogoda/b2b/smarthome

Попробовал, завелось с их интеграцией для HA. Данных показывает немного, но лучше, чем ничего. 

Не удалось получить ключ для своего аккаунта, на котором остался старый "тестовый" тариф. 
Создал новый акк, дали тариф "бесплатный".

**Comment by IATkachenko** [comment]
Да, выглядит как возрождение бесплатного API! В #127 будет добавляться поддержка. Это issue тогда прикрою.
