### ISSUE TITLE
Несовместимость с HA 2024.4

### ISSUE THREAD

**Issue by vmakeev** [IATkachenko/HA-YandexWeather#105]
### The problem

В HA 2024.4 убрали задепрекейченный ранее атрибут `ATTR_FORECAST` (https://github.com/home-assistant/core/pull/110761), теперь интеграция не стартует
### What version of the integration has the issue?

v3.1.3

### What version of Home Assistant Core has the issue?

2024.4 (rc)

### What type of installation are you running?

Home Assistant Container

### Anything in the logs that might be useful for us?

```txt

Setup failed for custom integration 'yandex_weather': Unable to import component: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
```

**Comment by IATkachenko** [comment]
Исправлено в [v3.2.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.2.0) 
pre-релиз, в данный момент.
