### ISSUE TITLE
Перестала работать после обновления на 2024.4.0

### ISSUE THREAD

**Issue by EvgenyBash** [IATkachenko/HA-YandexWeather#111]
### В чем проблема?

После обновления интеграция не загружается и выдаёт ошибку в логе.

### При использовании какой версии интеграции возникает проблема?

v3.1.3

### Какая версия Home Assistant используется?

2024.4.0

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
Регистратор: homeassistant.setup
Источник: setup.py:316
Первое сообщение: 09:25:59 (1 сообщений)
Последнее сообщение: 09:25:59

Setup failed for custom integration 'yandex_weather': Unable to import component: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/__init__.py", line 11, in <module>
    from .config_flow import get_value
  File "/config/custom_components/yandex_weather/config_flow.py", line 22, in <module>
    from .updater import WeatherUpdater
  File "/config/custom_components/yandex_weather/updater.py", line 13, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/yandex_weather/__init__.py", line 11, in <module>
    from .config_flow import get_value
  File "/config/custom_components/yandex_weather/config_flow.py", line 22, in <module>
    from .updater import WeatherUpdater
  File "/config/custom_components/yandex_weather/updater.py", line 13, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
```

**Comment by avenom** [comment]
Аналогичная проблема.

**Comment by NoAdO** [comment]
> Аналогичная проблема. Это связано с изменением тарифов погоды Яндекса? Т.е. интеграция больше не будет работать?

Врядли. Ошибка появляется именно после обновления до 2024.04 и в тексте лога `cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather'`, скорее всего изменилась логика работы с погодой, вроде что-то такое на весну и обещали

**Comment by krom** [comment]
Проблема в том, что если раньше прогноз погоды был просто прогнозом, который мог меняться от интеграции к интеграции, то сейчас в HA отдельно задается ежедневный, ежечасный и 2 раза в сутки прогнозы, соответственно необходимо четко указывать какая именно детализация используется
+ поменялась модель получения данных: если ранее прогноз погоды был атрибутом объекта, то сейчас он вынесен в отдельные методы и пользователь сам запрашивает прогноз в нужном разрезе - [документация](https://developers.home-assistant.io/docs/core/entity/weather/#weather-forecasts)

**Comment by Ptiolerwud** [comment]
Появилось ли решение? или ждать обновы интеграции?

**Comment by NoAdO** [comment]
> Появилось ли решение? или ждать обновы интеграции?

Ждать обновления интеграции. Если я всё правильно понимаю, автору нужно переписать то как теперь данные от Яндекса передаются в HA

**Comment by vkogan2005** [comment]
В бета-версии интеграции версии 3.2.0 всё работает.

**Comment by Ptiolerwud** [comment]
> В бета-версии интеграции версии 3.2.0 всё работает.

а где ветка бетки?

**Comment by b2rdetor** [comment]
> В бета-версии интеграции версии 3.2.0 всё работает.

а как ее поставить?

**Comment by krom** [comment]
Попробовал 3.2.0 - не падает, но я так подозреваю, что за счет отличия срезов получается прогноз всего на 2 дня
**Как поставить?**
Если ставили через HACS, то переустановить компонент и при выборе версии включить переключатель на beta

**Comment by IncognitoMSK** [comment]
Регистратор: homeassistant.config
Источник: config.py:1324
Первое сообщение: 18:24:46 (1 сообщений)
Последнее сообщение: 18:24:46

Invalid config for 'weather' from integration 'template' at configuration.yaml, line 70: 'forecast_template' is an invalid option for 'template.weather', check: forecast_template, please check the docs at https://www.home-assistant.io/integrations/template
Все равно не работает  (((

**Comment by Ptiolerwud** [comment]
> Регистратор: homeassistant.config Источник: config.py:1324 Первое сообщение: 18:24:46 (1 сообщений) Последнее сообщение: 18:24:46
> 
> Invalid config for 'weather' from integration 'template' at configuration.yaml, line 70: 'forecast_template' is an invalid option for 'template.weather', check: forecast_template, please check the docs at https://www.home-assistant.io/integrations/template Все равно не работает (((

Пробовал бетку, сразу заработало!

**Comment by IncognitoMSK** [comment]
> > Регистратор: homeassistant.config Источник: config.py:1324 Первое сообщение: 18:24:46 (1 сообщений) Последнее сообщение: 18:24:46
> > Invalid config for 'weather' from integration 'template' at configuration.yaml, line 70: 'forecast_template' is an invalid option for 'template.weather', check: forecast_template, please check the docs at https://www.home-assistant.io/integrations/template Все равно не работает (((
> 
> Пробовал бетку, сразу заработало!

Как раз после беты но у меня кастомная кастоматизация

**Comment by IncognitoMSK** [comment]
Заработало но нет прогноза только пишет ясно и температура ((

**Comment by IATkachenko** [comment]
> > В бета-версии интеграции версии 3.2.0 всё работает.
> 
> а как ее поставить?

Сейчас отмечу ее как current релиз

**Comment by b2rdetor** [comment]
> > > В бета-версии интеграции версии 3.2.0 всё работает.
> > 
> > 
> > а как ее поставить?
> 
> Сейчас отмечу ее как current релиз

спасибо, заработал прогноз, но не пойдет так. прогноз на неделю и почасовой не работает, в отличии от встроенного в ХА

**Comment by krom** [comment]
> спасибо, заработал прогноз, но не пойдет так. прогноз на неделю и почасовой не работает, в отличии от встроенного в ХА
Как я писал выше уже, похоже, что пришла погибель бесплатного компонента.
1. Яндекс ограничил параметры бесплатного архивного тарифа, старые пользователи продолжат работу, а вот новые уже не смогут зарегистрировать ключи
> Тариф для отображения погодных данных на сайтах. Позволяет получать фактические погодные значения и прогноз на 2 ближайших периода (ночь, утро, день или вечер). Лимит обращений — 50 запросов в сутки.
2. HA ввел 3 уровня детализации
2.1. почасовой прогноз - тут у нас не хватает данных, надо 24 записи за сутки, а яндекс отдает 4
2.2. 2 раза в сутки (день и ночь) - можем выкинуть из данных яндекса 2 из 4 запипей и оставить день и ночь за 2 дня
2.3. ежедневный прогноз - тут можно взять 1 из 4 записей за день и в итоге все равно получить прогноз за 2 дня

@IATkachenko может подкорректировать мой ответ, но в первом приближении, думаю, что я прав

**Comment by IATkachenko** [comment]
Да, все примерно так, за исключением некоторых особенностей: в прогнозе Яндекс отдает просто два следующих 6 часовых интервала, те 2 записи. Но без привязок к временным меткам.
Наиболее близкое что есть в НА для этого -- прогноз "2 раза в сутки", его и отдает интеграция. А дальше НА интерпритирует это как может. Поэтому иногда получается что в прогнозе он пишет день/ночь, а иногда ночь/ночь.

**Comment by b2rdetor** [comment]
> Да, все примерно так, за исключением некоторых особенностей: в прогнозе Яндекс отдает просто два следующих 6 часовых интервала, те 2 записи. Но без привязок к временным меткам. Наиболее близкое что есть в НА для этого -- прогноз "2 раза в сутки", его и отдает интеграция. А дальше НА интерпритирует это как может. Поэтому иногда получается что в прогнозе он пишет день/ночь, а иногда ночь/ночь.

То есть лучше, чем сейчас уже не сделать? хм, похоже придется искать другой погодный сервис (яндекс был нужен для второго местоположения в дополнение к встроенному сервису ХА)
