### ISSUE TITLE
Странное поведение в кастомной карточке custom:clock-weather-card

### ISSUE THREAD

**Issue by alexanderznamensky** [IATkachenko/HA-YandexWeather#112]
### The problem

После обновления компонента на v3.2.0 и НА 2024.4.0 не показывает правильно прогноз:
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/0f41aebb-d696-42d0-8a8b-cefff44770f1)

При этом эта же карточка другие источники погоды показывает правильно.

### What version of the integration has the issue?

v3.2.0

### What version of Home Assistant Core has the issue?

2024.4.0

### What type of installation are you running?

Home Assistant Supervised

**Comment by alexanderznamensky** [comment]
Доброе утро, Игорь.
В дефолтной все корректно отображается.
Но, вот что не понятно, так это то, что в кастомной карточке другие сущности погоды (gismeteo, Meteorological institute, AccuWeather, Open Meteo, OpenWeatherMap) отображаются так же правильно как и в дефолтной.
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/a48c2b82-8e77-4fed-97dc-57deaaeaa9e9)
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/2a381d89-4d2b-4659-8897-ed79d205ae79)
 а у нас вот так:
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/07199671-8859-4525-939a-76533b77b305)
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/69b420a7-0ea0-4f9b-bbc3-f4bba1a29a7c)

**Comment by IATkachenko** [comment]
Похоже что карточка рассчитана на недельный прогноз, а Яндекс отдает прогноз на два 6 часовых интервала, который я прокидываю в HA как "прогноз 2 раза в сутки".
Так что выглядит все правильно.
ps. вангую что можно найти момент когда в карточке будет виден прогноз на два дня (когда 6 часовые интервалы будут попадать на разные дни)

**Comment by alexanderznamensky** [comment]
Странно, что раньше на НА 2024.3.* и v3.1.3 интеграции эта карточка корректно работала с двухдневным прогнозом Яндекса....

**Comment by IATkachenko** [comment]
У меня она вообще прогноз не показывает в дефолтной конфигурации...

**Comment by IATkachenko** [comment]
> Странно, что раньше на НА 2024.3.* и v3.1.3 интеграции эта карточка корректно работала с двухдневным прогнозом Яндекса....

![изображение](https://github.com/IATkachenko/HA-YandexWeather/assets/17473830/1d50f251-4c0b-4e4c-86ba-c534f3bb8e94)
```yaml
type: custom:clock-weather-card
entity: weather.yandex_weather
hourly_forecast: true
```

**Comment by alexanderznamensky** [comment]
собственно, у меня так и было )))
это не может быть из-за того, что атритбуты прогноза в новой версии интеграции поменяли название (дополнились префиксом native_*)?

**Comment by alexanderznamensky** [comment]
чудеса.... но прогноз в (панель разработчика -> состояние) не показывает:
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/251c56e1-a7ca-4750-832a-19ee1480e81c)
у weather.yandex_weather он есть:
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/513354f3-7c27-4317-ab4d-b8995ff8f225)

**Comment by IATkachenko** [comment]
Да, это именно из-за этого.
Как пишет HA -- https://github.com/home-assistant/core/blob/f2fe2c45109b01d779f479a9e866f3c11ec868f7/homeassistant/components/weather/__init__.py#L177
```
All attributes are in native units and old attributes kept 
    for backwards compatibility.
```

Начиная с нашей версии 3.1.0 в части атрибутов ничего не менялось -- вот тут вся магия делается https://github.com/IATkachenko/HA-YandexWeather/blame/main/custom_components/yandex_weather/updater.py#L111, так что думаю в HA умолчания поправили.
Но с этим можно работать.
Сейчас немного поэкспериментирую и сегодня-завтра выложу фикс.

**Comment by IATkachenko** [comment]
> чудеса.... но прогноз в (панель разработчика -> состояние) не показывает:

Это нормально: в 2024.4 HA разделил получение прогноза и текущей погоды. Яндекс так не умеет, а 2 API запроса мы слать (у нас их всего 50 в день) не хотим, поэтому живем с прогнозом внутри объекта погоды.

**Comment by alexanderznamensky** [comment]
тогда все более-мене понятно )))

**Comment by alexanderznamensky** [comment]
выглядит отлично! ждем обновление!
Спасибо большое за вашу работу!

**Comment by IATkachenko** [comment]
Исправлено в [v3.2.1](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.2.1)

**Comment by alexanderznamensky** [comment]
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/9a3006e5-4a0a-4009-8bb6-e0ebbc362911)
Спасибо, Игорь!
