### ISSUE TITLE
После перезагрузки Home Assistant не подтягиваются старые значения прогноза.

### ISSUE THREAD

**Issue by dmitkam** [IATkachenko/HA-YandexWeather#115]
### В чем проблема?

Можно ли сделать подтяжку старых значений прогроза, после перезагрузки НА ?

### При использовании какой версии интеграции возникает проблема?

v3.2.1

### Какая версия Home Assistant используется?

	core-2024.4.2

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

**Comment by IATkachenko** [comment]
Так и было.
Это должно делаться через атрибуты, которые шатали в последних релизах, проверю в районе выходных.

**Comment by IATkachenko** [comment]
Исправлено в [v3.2.3](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.2.3)
