### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by Rafilzak** [IATkachenko/HA-YandexWeather#13]
После загрузки через hacs не могу найти интеграцию в настройках HA, соответственно не могу указать api key

**Comment by IATkachenko** [comment]
Попробуйте очистить кэш браузера.
Ну и логи имеет смысл проверить при загрузке: там должно быть сказано что HA нашел custom integration yandex weather.

**Comment by Rafilzak** [comment]
> Попробуйте очистить кэш браузера. Ну и логи имеет смысл проверить при загрузке: там должно быть сказано что HA нашел custom integration yandex weather.

очистка кеша помогла, спасибо

**Comment by IATkachenko** [comment]
Отлично, добавлю информацию в readme.
