### ISSUE TITLE
В истории виджета home assistant показывается не температура, а погода (например, солнечно, облачно), можно это поправить?

### ISSUE THREAD

**Issue by Nerd0o0** [IATkachenko/HA-YandexWeather#16]

**Comment by IATkachenko** [comment]
Нет, так работает Home Assistant: состояние погоды это солнечно, облачно итд.

Если нужна история температуры (давления, влажности, скорости и направления ветра) -- активируйте соответствующий сенсор (он деактивирован по умолчанию) на странице устройства интеграции.

**Comment by Nerd0o0** [comment]
Активированы, добавлены в виджет на главной странице, кликая в нужное место можно увидеть историю температуры. Спасибо, это именно то, что мне нужно
