### ISSUE TITLE
Интервалы прогноза погоды

### ISSUE THREAD

**Issue by GerAltlt** [IATkachenko/HA-YandexWeather#25]
### В чем проблема?

Предложение по улучшению проекта. 
Интуитивно не понятно на какие периоды вперед показана погода. Яндекс Погода бесплатно предоставляет прогноз на 4 периода. Как предложение, у прогноза на перспективу добавить либо временные интервалы (0:00-6:00, 6:00-12:00, 12:00-18:00, 18:00-0:00), либо названия периодов (утро, полдень, вечер, ночь). Например, Пт (утро).

### При использовании какой версии интеграции возникает проблема?

0.8

### Какая версия Home Assistant используется?

2022.4.6

### Какой способ установки Home Assistant используется?

Home Assistant OS

**Comment by IATkachenko** [comment]
К сожалению, названия некуда добавить.
HA не предлагает подходящих мест.
Прогноз должен быть собран из класса `Forecast` 
https://github.com/home-assistant/core/blob/be0fbba52308fe4f7481c59653b8999457481910/homeassistant/components/weather/__init__.py#L68 
```python
class Forecast(TypedDict, total=False):
    """Typed weather forecast dict."""

    condition: str | None
    datetime: str
    precipitation_probability: int | None
    precipitation: float | None
    pressure: float | None
    temperature: float | None
    templow: float | None
    wind_bearing: float | str | None
    wind_speed: float | None
```
И нет никакой возможности добавить что-то еще.
В `datetime` записывается время интервала https://github.com/IATkachenko/HA-YandexWeather/blob/94c422dd5f99d05d5ce08900e14118da48011ca1/custom_components/yandex_weather/updater.py#L189
```python
  f_datetime = datetime.utcnow()
  for f in r["forecast"]["parts"]:
    result.setdefault(ATTR_FORECAST, [])
    forecast = Forecast()
    f_datetime += timedelta(hours=24 / 4)
    forecast[ATTR_FORECAST_TIME] = f_datetime.isoformat()  # type: ignore
```

которое интерпретируется HA (на самом деле этим занимается UI) так, как он считает нужным.

В нашем случае:
  * стандартная карточка видит что прогнозы далеко друг от друга и показывает только день недели
  * карточка  состояния компонента `weather` тоже види что прогнозы далеко дург от друга и не показывает подробности.

Так что, к сожалению, на уровне интеграции ничего сделать нельзя.
