### ISSUE TITLE
Проблема с кастомизацией

### ISSUE THREAD

**Issue by evsmorodin** [IATkachenko/HA-YandexWeather#26]
### В чем проблема?

Через customize ради интереса решил попробовать впихнуть значение датчика, но получил вот такое...
Уже не знаю что ещё можно сделать, кастомизацию удалил, интеграцию уже несколько раз и переустанавливал, но эта запись продолжает там светиться...
![изображение](https://user-images.githubusercontent.com/7508931/164701327-1ac45c5f-b819-4f51-8100-3bbb3bdf2749.png)

Может кто знает как это вылечить?

### При использовании какой версии интеграции возникает проблема?

0.8

### Какая версия Home Assistant используется?

2022.4.5

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

**Comment by IATkachenko** [comment]
Как я понимаю при обновлении проблема сохраняется?

Посмотрите что у вас в customize.yaml написано (или как он там называется).  
Дальше в сторону storage идти надо, чтобы разобраться. 

К сожалению, что-то более дельное подсказать могу.

**Comment by evsmorodin** [comment]
Как-то оно вылечилось, но как именно я так и не понял, есть подозрение, что помогло удаление файла кастомизации, но это не точно...

Вопрос другой теперь:
![изображение](https://user-images.githubusercontent.com/7508931/164706538-025b9ca0-9c66-4737-b455-4d686fa94ea5.png)
как тут hPa изменить на мм ртутного столба?

**Comment by IATkachenko** [comment]
Как это ни странно -- никак.
По двум с половиной причинам:
1. Это issue не про это и валить все в кучу -- не правильно по отношению к тому, кто после вас будет искать решение своей проблемы. (я сейчас приберусь и утащу в другое issue это).
2. С точки зрения HA mmHg -- это не единица давления
3a. Карточка в UI думает что давление всегда в hPa и мы подстраиваемся под это, см #8 
3b. Карточка состояния думает что давление в системных единицах (Pa)
3c. Если попытаться указать единицы давления, то HA сконвертиурет его в системные (если сможет) и на карточке состояния давление будет правильное, а на карточке UI -- нет
3d. А если указать что давление в mmHg, то все вообще сломается.

Поэтому в интеграции и живет отдельный сенсор с давлением в mmHg, который никому не говорит что он измеряет давление.
