### ISSUE TITLE
Просьба добавить поддержку анимированных значков

### ISSUE THREAD

**Issue by vring0** [IATkachenko/HA-YandexWeather#30]
Спасибо за поддержку Яндекс погоды, возможно ли добавить поддержку анимированных  [значков](https://www.amcharts.com/free-animated-svg-weather-icons/), которые используются в этом репозитории https://github.com/bramkragten/weather-card ? Я думаю в настройках интеграции можно будет сделать переключение значков Яндекса на анимированные.
![cloudy-day-2](https://user-images.githubusercontent.com/34909289/166414491-ed303511-df32-43e9-935a-83c4cb009be8.svg)
![cloudy-night-1](https://user-images.githubusercontent.com/34909289/166414494-77815101-4317-420a-a909-186fe035b39c.svg)
![night](https://user-images.githubusercontent.com/34909289/166414496-214cc9a5-4f89-4f58-8cfb-e2649cca1d7a.svg)
![rainy-2](https://user-images.githubusercontent.com/34909289/166414498-a5a64da7-2de3-4667-a70b-67805733deb3.svg)
![rainy-6](https://user-images.githubusercontent.com/34909289/166414500-516b2bd7-f2e6-41e0-91bc-df87b595ea60.svg)
![snowy-2](https://user-images.githubusercontent.com/34909289/166414501-33b51ffe-13b1-481a-82f7-97d66cacb65c.svg)
![snowy-4](https://user-images.githubusercontent.com/34909289/166414503-c4ff9b43-e4b9-4559-ad9b-7a544db36b6e.svg)

**Comment by IATkachenko** [comment]
Я подумаю как это лучше сделать.
Получается что будет три опции:
1. стандартные значки от HA;
2. значки от Яндекса (как сейчас);
3. предложенные тут.

**Comment by vring0** [comment]
> Всем желающим предлагается поучаствовать в определении того как разные состояния погоды будут отображаться. Принцип такой: ключи json'a -- состояние погоды по Яндексу, значения -- или картинка из [animated weather card](https://github.com/bramkragten/weather-card/tree/master/icons/animated), или картинка в зависимости от того день сейчас или ночь. Пока у меня вот такой маппинг получается:
> 
> ```json
> {
>     "clear": {
>         "day": "day",
>         "night": "night",
>     },
>     "partly-cloudy": {
>         "day": "cloudy-day-1",
>         "night": "cloudy-night-1",
>     },
>     "cloudy": {
>         "day": "cloudy-day-2",
>         "night": "cloudy-night-2",
>     },
>     "overcast": {
>         "day": "cloudy-day-3",
>         "night": "cloudy-night-3"
>     },
>     "drizzle": "rainy-1",
>     "light-rain": "rainy-2",
>     "rain": "rainy-3",
>     "moderate-rain": "rainy-4",
>     "heavy-rain": "rainy-5",
>     "continuous-heavy-rain": "rainy-6",
>     "showers": "rainy-7",
>     "wet-snow": "snowy-3",
>     "light-snow": "snowy-1",
>     "snow": "snowy-4",
>     "snow-showers": "snowy-5",
>     "hail": "snowy-6",
>     "thunderstorm": "thunder",
>     "thunderstorm-with-rain": "thunder",
>     "thunderstorm-with-hail": "thunder",
> }
> ```
> 
> Открыт для идей и предложений.
> 
> Ориентировочно, после выходных будет релиз с этой штукой (сейчас локально у себя тестирую).

Отлично! Если буду успевать, то обязательно помогу.

**Comment by IATkachenko** [comment]
Добавлено в[ v0.10.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v0.10.0)
