### ISSUE TITLE
Ошибки при перезапуске HA после установки интеграции

### ISSUE THREAD

**Issue by ANS-spb** [IATkachenko/HA-YandexWeather#33]
### В чем проблема?

Интеграция успешно добавляется в HACS, устанавливается, но объекты интеграции недоступны.
Ключ API проверил curl-ом, с https://api.weather.yandex.ru/v2/informers погода отдаётся. Тариф выбран "Погода на вашем сайте", как в мануале. Проверял в HA 2022.6.6 и 2022.6.7.

### При использовании какой версии интеграции возникает проблема?

v0.10.0

### Какая версия Home Assistant используется?

core-2022.6.7

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Есть что-нибудь полезное в логе?

```txt
Logger: homeassistant.components.sensor
Source: custom_components/yandex_weather/sensor.py:202 
Integration: Сенсор (documentation, issues) 
First occurred: 17:06:10 (2 occurrences) 
Last logged: 17:06:10

Error adding entities for domain sensor with platform yandex_weather
Error while setting up yandex_weather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/sensor.py", line 202, in async_added_to_hass
    self._attr_native_value = datetime.fromisoformat(state.state)
ValueError: Invalid isoformat string: 'unavailable'
```

**Comment by ANS-spb** [comment]
Сорри, всё заработало, пока экспериментировал с другой интеграцией :)
Не знаю, что помогло, но всё работает

**Comment by ANS-spb** [comment]
Да, примерно 30 минут. Первая мысль была про ещё не активированный (или как это называется?) ключ API Яндекса, и скорее всего, это оно и было, как я думаю :)
Странно только, что curl-ом он мне данные отдавал с этим же ключом

**Comment by IATkachenko** [comment]
Там в другом дело: до первого нормального получения данных от Яндекса интеграция попыталась восстановить свое предыдущее состояние. И предыдущим состоянием было `unavailable`, из которого она не смогла сварить дату последнего обновления.
Собственно это вскрывает две проблемы:
1. нефиг пытаться; 
2. нужно чтобы данные забирались и записывались сразу, при добавлении.

Хотя я допускаю что при первом получении могло что-то пойти не так, `unavailable` записался как результат (хотя, если я правильно помню, то что интеграция добавилась автоматически означает что данные она получить может) и мы наблюдаем то, что наблюдаем.

В общем мне есть над чем подумать и что поправить.

**Comment by ANS-spb** [comment]
Помню, что когда ключ ещё действительно не работал после его создания, интеграция не давала себя настроить и ругалась. Видимо, в части первоначальной проверки ключа всё хорошо. 
Потом, наконец, ключ заработал, интеграция добавилась, счётчик использования ключа в кабинете Яндекса прибавил единичку, но вышла вышеописанная ошибка. 
Я пробовал удалять интеграцию, рестартить ХА и добавлять снова с тем же результатом. Пробовал откатывать версию ХА на предыдущую и снова добавлять интеграцию, ошибка та же. 
Потом, спустя примерно полчаса (как вы и описали) и очередного ребута ХА интеграция заработала и больше в журнал не ругалась.

**Comment by IATkachenko** [comment]
Спасибо, поправлю в ближайшем релизе.

**Comment by maks23rus** [comment]
Приветствую. Прошу помочь и уточнить куда вписывать API-ключ? Уже час потратил, не могу найти это поле.

**Comment by maks23rus** [comment]
> Приветствую. Прошу помочь и уточнить куда вписывать API-ключ? Уже час потратил, не могу найти это поле.

Спасибо. Разобрался. Нужно было добавить интеграцию в HA. А я подумал что достаточно только установить в HACS.
