### ISSUE TITLE
Здраствуйте к сожалению не работает

### ISSUE THREAD

**Issue by Fiark** [IATkachenko/HA-YandexWeather#4]
![image](https://user-images.githubusercontent.com/90027145/151159593-b7ce87a1-65e1-4fa4-ab3d-705fdf1afc73.png)
![image](https://user-images.githubusercontent.com/90027145/151159654-12362dae-405e-4585-973f-e5a11e85b0d4.png)
Тариф правильный, ключ копирую.

**Comment by IATkachenko** [comment]
@Fiark, добрый день.

`home-assistnat.log` приложите, пожалуйста.
Желательно, с включенным дебагом для интеграции. Посмотрим что у вас происходит.

**Comment by fttomas** [comment]
Тоже столкнулся с такой проблемой.
При создании ключа в Я. разработчике, несмотря на выбранный тариф, проставился всё равно "тестовый", а не "для сайта". Также при смене через интерфейс показывает, что всё изменилось, на самом деле нет, меняется в течении 15-20 минут).
Поэтому от меня рекомендация: создаете ключ, ждете ~10 минут, проверяете тариф, если что меняете на нужный, ждете ~10 минут и только после этого пытаетесь добавить интеграцию.

**Comment by IATkachenko** [comment]
Добавил сообщение о том что может потребоваться до 30 минут для обновления ключа на стороне Яндекса.
В master версия уже с этим сообщением. В WiKi тоже добавил информации.
