### ISSUE TITLE
Добавление атрибутов в weather компонент

### ISSUE THREAD

**Issue by IATkachenko** [IATkachenko/HA-YandexWeather#40]
### Оригинальная идея @glebsterx в https://github.com/IATkachenko/HA-YandexWeather/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **glebsterx** July 21, 2022</sup>
Предложение:
добавить в атрибуты сущности по-умолчанию `weather.yandex_weather` все, что Яндекс отдает в json, а именно
```
feels_like
temp_water
pressure_mm (для тех кто хочет в mmHg)
wind_gust
...
```
Мотивация: если данные обновляются раз в полчаса -- то отслеживать состояние не имеет большого смысла (имеет конечно, но хз зачем). Держать по сенсору на каждый параметр тоже не всегда удобно, так пусть тогда все данные будут в атрибутах, если это не очень сложно -- их оттуда можно будет вытащить в шаблоны =)

Не знаю сломается ли что-нибудь если вытащить атрибуты еще и прогнозов -- но там тоже было бы можно =)
Спасибо за внимание =)</div>

**Comment by glebsterx** [comment]
еще можно было бы добавить `yandex_condition` чтобы не путаться (это я путаюсь, как другие -- не знаю), который будет содержать оригинальное название погодных условий от Яндекса =)

**Comment by IATkachenko** [comment]
Добавлено в [v1.1.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v1.1.0).

`pressure_mm` не добавлял.
Сейчас для этого есть:
  1. настройка единиц в компоненте weather;
  2. отдельный сенсор.

**Comment by glebsterx** [comment]
спасибо!
