### ISSUE TITLE
Пропала влажность

### ISSUE THREAD

**Issue by Haronych** [IATkachenko/HA-YandexWeather#43]
### В чем проблема?

С последним обновлением из прогноза пропала влажность

### При использовании какой версии интеграции возникает проблема?

 v1.0.0

### Какая версия Home Assistant используется?

core-2022.7.6

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Есть что-нибудь полезное в логе?

```txt
Logger: homeassistant.components.sensor
Source: custom_components/yandex_weather/sensor.py:206
Integration: Сенсор (documentation, issues)
First occurred: 10:01:30 (4 occurrences)
Last logged: 10:04:34

Error adding entities for domain sensor with platform yandex_weather
Error while setting up yandex_weather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/sensor.py", line 206, in async_added_to_hass
    self._attr_native_value = datetime.fromisoformat(state.state)
ValueError: Invalid isoformat string: 'unknown'
```

**Comment by Haronych** [comment]
temperature: 28
temperature_unit: °C
pressure: 741.81
pressure_unit: mmHg
wind_bearing: 45
wind_speed: 2.1
wind_speed_unit: m/s
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2022-07-26T14:33:16.091452'
  wind_bearing: 45
  condition: cloudy
  precipitation_probability: 0
  temperature: 28
  templow: 28
  pressure: 741.81
  wind_speed: 2.4
  precipitation: 0
- datetime: '2022-07-26T20:33:16.091452'
  wind_bearing: 360
  condition: cloudy
  precipitation_probability: 0
  temperature: 24
  templow: 21
  pressure: 741.81
  wind_speed: 1.1
  precipitation: 0

attribution: Data provided by Yandex Weather
entity_picture: https://yastatic.net/weather/i/icons/funky/dark/bkn_d.svg
friendly_name: Москва

**Comment by IATkachenko** [comment]
Ошибка в логе -- это не про влажность. Такое случается если перезапустить HA до того как интеграция заберет данные.
Тогда в состояние сенсора "время погодной информации" запишется `unknown`, и при восстановлении состояния при перезапуске вы увидите то, что видите.

А вот куда влажность делась -- пока загадка. У меня в текущем состоянии она есть (правда 92%, что настараживает).
А в прогнозе тоже нет.

Спасибо, посмотрю что происходит.

**Comment by IATkachenko** [comment]
Куда актуальная влажность делась -- нашел.

**Comment by IATkachenko** [comment]
А в прогнозе влажности и не должно быть.

Сейчас выкачу fix-релиз.

**Comment by IATkachenko** [comment]
Исправлено в [v1.0.1](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v1.0.1)
