### ISSUE TITLE
Перевести на русский сенсор погоды.

### ISSUE THREAD

**Issue by uefik** [IATkachenko/HA-YandexWeather#48]
### В чем проблема?

Что бы озвучить погоду использую Google Home колонки, в автоматизации используются значения сенсора погоды для HA :
 Сейчас `{{states(''sensor.yandex_weather_condition_homeassistant'')}}` , пробовал и Яндекс и original все воспроизводятся по аглицки, В интеграции есть json для перевода значений на русский, как получать значение погоды уже переведённое?
Или я ошибаюсь с сенсором?

### При использовании какой версии интеграции возникает проблема?

1.1.0

### Какая версия Home Assistant используется?

2022.8.4

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

**Comment by IATkachenko** [comment]
За то, в каком виде вы получаете состояние отвечает frontend. Интеграция на это может влиять только в виде исходных данных.
А дальше начинаются неприятности: чтобы корректно отображать `weather` компонент, состояние должно быть из списка ожидаемых HA. Сейчас делается mapping состояний Яндекса в состояния HA и запросы идут на английском. Если делать поддержку языков, то такой mapping нужен для каждого языка.

Может быть, имеет смысл сделать промежуточное решение, с ограниченным набором поддерживаемых языков...

Правильное решение -- использовать переводы в frontend. Про это вот такой PR есть https://github.com/home-assistant/core/pull/65743, но он, пока, не близко к релизу...

**Comment by uefik** [comment]
Придётся написать шаблон под все 19 значений погоды, и в нём переводить значения.

**Comment by IATkachenko** [comment]
На сколько я знаю, так и делают.
Я может до конца недели добавлю поддержку выбора языка: как сделать -- понятно. Вопрос исключительно в том что это делается в неправильном месте.

**Comment by IATkachenko** [comment]
Добавлено в [v1.2.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v1.2.0)

**Comment by IATkachenko** [comment]
Итак, свершилось! HA теперь умеет переводить все https://developers.home-assistant.io/blog/2022/12/01/entity_translations/
В ближайшее время смигрируем на этот способ.
