### ISSUE TITLE
При перезапуске не восстанавливаются предыдущие значения

### ISSUE THREAD

**Issue by alexanderznamensky** [IATkachenko/HA-YandexWeather#53]
### В чем проблема?

Точно сказать не могу, но где-то в районе недели интеграция работает, а потом перестает (замечено на трех разных серверах).
Ошибок в логе 2 при запуске:
```
Logger: homeassistant.components.sensor
Source: custom_components/yandex_weather/sensor.py:198
Integration: Сенсор (documentation, issues)
First occurred: 08:03:58 (2 occurrences)
Last logged: 08:03:58

Error adding entities for domain sensor with platform yandex_weather
Error while setting up yandex_weather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/sensor.py", line 198, in async_added_to_hass
    self._attr_native_value = datetime.fromisoformat(state.state)
ValueError: Invalid isoformat string: 'unavailable'
```
```
Logger: homeassistant.components.weather
Source: util/pressure.py:53
Integration: Weather (documentation, issues)
First occurred: 08:03:58 (2 occurrences)
Last logged: 08:03:58

Error adding entities for domain weather with platform yandex_weather
Error while setting up yandex_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/weather.py", line 121, in async_added_to_hass
    converter(
  File "/usr/src/homeassistant/homeassistant/util/pressure.py", line 53, in convert
    raise TypeError(f"{value} is not of numeric type")
TypeError: None is not of numeric type
```

### При использовании какой версии интеграции возникает проблема?

v1.2.0

### Какая версия Home Assistant используется?

Home Assistant 2022.9.2

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Дополнительная информация

Чинится простой переустановкой (даже перезагрузка не требуется).

**Comment by IATkachenko** [comment]
Проблема в том, что при рестарте интеграция пытается подтянуть предыдущие показания сенсоров, которые у вас не сохраняются. Это не должно вызывать никаких ошибок, но что-то идет не так.

Добавлю дополнительных проверок, чтобы интеграция не пыталась восстанавливать состояние, если его нет.

Чтобы все продолжило работать переустанавливаться не обязательно: оно починится само при следущем обновлении данных или если вызвать обновлени в ручную.

**Comment by alexanderznamensky** [comment]
Игорь, спасибо за быстрый ответ!

Должен добавить, что ни перезагрузка, ни долгое ожидание (несколько дней), ни ручное обновление не дают результатов (само не чинится). Т.е. если перестало работать, нужно переустанавливать.

**Comment by IATkachenko** [comment]
Это странно, потому что блок, в котором возникают ошибки вызывается только в момент старта интеграции.

Хочется, в таком случае, взглянуть на debug-лог, чтобы лучше понять что происходит.

**Comment by alexanderznamensky** [comment]
Сейчас на всех трех серверах интеграции работают.
Если на каком-то сервере перестанет работать, то попробую поймать этот момент и пришлю лог вам.

**Comment by alexanderznamensky** [comment]
вот - началось:
![image](https://user-images.githubusercontent.com/65254375/190501021-3ced8781-50ef-443c-adea-2e8483b8f5c4.png)

Logger: homeassistant.components.weather
Source: util/pressure.py:53
Integration: Weather (documentation, issues)
First occurred: 14 сентября 2022 г., 17:40:00 (358 occurrences)
Last logged: 23:20:00

Error adding entities for domain weather with platform yandex_weather
Error while setting up yandex_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/weather.py", line 121, in async_added_to_hass
    converter(
  File "/usr/src/homeassistant/homeassistant/util/pressure.py", line 53, in convert
    raise TypeError(f"{value} is not of numeric type")
TypeError: None is not of numeric type

Logger: homeassistant.components.sensor
Source: custom_components/yandex_weather/sensor.py:198
Integration: Сенсор (documentation, issues)
First occurred: 14 сентября 2022 г., 17:40:00 (358 occurrences)
Last logged: 23:20:00

Error adding entities for domain sensor with platform yandex_weather
Error while setting up yandex_weather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_weather/sensor.py", line 198, in async_added_to_hass
    self._attr_native_value = datetime.fromisoformat(state.state)
ValueError: Invalid isoformat string: 'unavailable'

**Comment by IATkachenko** [comment]
> Хочется, в таком случае, взглянуть на debug-лог, чтобы лучше понять что происходит.

Можно фрагменты `home-assistnat.log` с логами интеграции на уровне `debug`, а не следы exception'ов в UI?
Хочется видеть начало (момент старта HA), последнее успешное обновление и собственно момент возникновения ошибки.

У  вас оно очень часто выстреливает (судя по тому что я вижу -- 358 раз за 1,5 дня, хотя обновлений должно быть не больше 48 в день). Хочется понять что происходит с системой и почему мы видим то, что видим.

**Comment by alexanderznamensky** [comment]
пульну весь лог вам
[home-assistant.log](https://github.com/IATkachenko/HA-YandexWeather/files/9579165/home-assistant.log)

**Comment by IATkachenko** [comment]
`debug` логов от интеграции там не видно. Какие-нибудь логи делу помогут "как-нибудь".

То что я сейчас вижу -- у вашего хоста проблемы с сетью и сетевыми запросами на разные сервисы, в том числе, которые использует эта интеграция. 

_ps. лог на 35тыс строк с ошибками примерно 5-6 интеграций и самописных сенсоров и не содержащий **дважды** запрошенной информации -- совсем не то, что способствует желанию помочь разобраться с проблемой._

**Comment by alexanderznamensky** [comment]
Игорь, доброе утро. Прошу прощения....
Скорее всего сервер, который на даче и лог от которого я прислал (подключен к мобильному нестабильному интернету), может не быть показательным (предполагаю, что там и ошибки из-за этого).
Я не очень большой гуру в НА (и тем более в логах). Если у вас будет время и возможность дать мне четкие инструкции, я их прилежно выполню, обещаю )))

**Comment by IATkachenko** [comment]
Это, в целом, подтверждает версию о сетевых проблемах и более-менее объясняет происходящее. Я примерно представляю что нужно сделать чтобы все было хорошо. Но без сети у вас интеграция всеравно не заработает ;)

debug логи включаются в `configuration.yaml` так:
```yaml
logger:
  default: warning
    custom_components.yandex_weather: debug
```
и перезапустить HA.
_(надо будет в readme или issue template утащить это...)_

**Comment by alexanderznamensky** [comment]
Игорь, спасибо.

Как только на одном из домашних серверов (которые с хорошим интернетом) появится проблема, сразу пришлю Вам дебаг-лог.

**Comment by alexanderznamensky** [comment]
Игорь, спасибо за update! Теперь работает намного надежнее!

**Comment by IATkachenko** [comment]
Ага, те вашу проблему v1.2.1 тоже решила. 
Отлично!

**Comment by alexanderznamensky** [comment]
Похоже, что решила - пока ни одного сбоя не было! Я даже смог победить патреон, чтобы сказать вам спасибо )
