### ISSUE TITLE
Bug: получения анимированной иконки 

### ISSUE THREAD

**Issue by vring0** [IATkachenko/HA-YandexWeather#59]
### В чем проблема?

Получаю не валидный [URL](https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/icons/Ясно.svg) на анимированную иконку в атрибуте сущности погоды .

Реализация была добавлена в рамках этого Issue #30 

### При использовании какой версии интеграции возникает проблема?

1.2.2

### Какая версия Home Assistant используется?

2022.11.4

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Дополнительная информация

Список атрибутов:

![image](https://user-images.githubusercontent.com/34909289/204236957-fbe00ff8-0442-43d7-b671-18d4cc0638ac.png)

Ошибка при переходе на [URL](https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/icons/Ясно.svg) иконки:

![image](https://user-images.githubusercontent.com/34909289/204237083-418cdbbb-4ac3-40a5-ba27-369fa04f04d5.png)

**Comment by IATkachenko** [comment]
В атрибут `yandex_confition` попадает переведенное состояние, после того как переводы добавили вот тут https://github.com/IATkachenko/HA-YandexWeather/commit/693faaea6bedeca0418f5bde10cca2bf918f6a89

Поправлю в ближайшее время.

Извините за неудобство...

**Comment by vring0** [comment]
> В атрибут `yandex_confition` попадает переведенное состояние, после того как переводы добавили вот тут [693faae](https://github.com/IATkachenko/HA-YandexWeather/commit/693faaea6bedeca0418f5bde10cca2bf918f6a89)
> 
> Поправлю в ближайшее время.
> 
> Извините за неудобство...

Понял. Нет проблем)

**Comment by IATkachenko** [comment]
Исправлено в [v1.2.3](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v1.2.3).
