### ISSUE TITLE
Работало, но не долго.

### ISSUE THREAD

**Issue by redtaburett** [IATkachenko/HA-YandexWeather#7]
Яндекс заблокировал API за привышение количества запросов, хотя выставлено было 48. Ещё вчера обратил внимание, что данные то были, то не было. А сегодня вообще, данные пропали и видимо дозапрашивался) В кабинете показал, что было 72 запроса до блокировки. Работало 3-4 дня, превышений небыло.

**Comment by IATkachenko** [comment]
Перезапускали HA (или он сам перезапускался)?
При каждом запуске делается первый запрос, чтобы получить погодные данные. Из-за этого могут получаться "лишние" запросы. 

Я подумаю как это можно обойти, но пока хорошего способа нет. Только уменьшить количество запросов.

**Comment by redtaburett** [comment]
Да, перезапускал. Я только пробую HA, у меня всё на начальной стадии, поэтому постоянные перезапуски. Но сегодня почему то ещё долгое время не показывал данные, хотя видно было, что запросы были. И вчера почему то проблески были, то показывает данные, то не показывает. Пока снёс, вернусь позже, буду иметь в виду про перезапуски.
