### ISSUE TITLE
Ошибка преобразования направления ветра

### ISSUE THREAD

**Issue by mexpetrov** [IATkachenko/HA-YandexWeather#74]
### В чем проблема?

После обновления до 2023.4.. направление ветра стало отдавать в числовом формате, я так понимаю в градусах без текстового "южный" и т.п. можно это поправить или подскажите где самому искать в коде.

### При использовании какой версии интеграции возникает проблема?

2.0.3

### Какая версия Home Assistant используется?

2023.4.6

### Какой способ установки Home Assistant используется?

Home Assistant Supervised

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

**Comment by IATkachenko** [comment]
Спасибо! Я почти знаю что там приключилось: в HA поменялся формат файла переводов, а я туплю с обновлением.
У вас еще, наверное, `sensor.yandex_weather_condition_yandex` и `sensor.yandex_weather_condition` показывают не совсем то, что нужно.

**Comment by mexpetrov** [comment]
Yandex Weather Condition Yandex отдаёт вроде верно, у меня не все сенсоры используются и проблема только с Yandex Weather Wind bearing

**Comment by IATkachenko** [comment]
Да, состояния тоже не транслируются:
![изображение](https://user-images.githubusercontent.com/17473830/235617530-0d9229a6-1237-42bb-9d17-40c38afe2ff5.png)
А Яндексовое состояние правильное потому что переводится внутри интеграции.

Хех... опять мажорную версию поднимать...

**Comment by IATkachenko** [comment]
Исправлено в [v3.0.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.0.0)
