### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by robulanetteam** [IATkachenko/HA-YandexWeather#77]
### В чем проблема?
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yandex_weather/__init__.py", line 50, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```
### При использовании какой версии интеграции возникает проблема?

3.0.0

### Какая версия Home Assistant используется?

Home Assistant 2023.5.2

### Какой способ установки Home Assistant используется?

Home Assistant Container

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

### Есть что-нибудь полезное в логе?

```txt
Перестало работать после обновления homeassistant
```

**Comment by IATkachenko** [comment]
Версия точно 3.0.0? Вот в этом коммите, https://github.com/IATkachenko/HA-YandexWeather/commit/cf097c8dce8264e52a4d3a7a4882e25acadb2e46, который появился в `v2.0.0`, все было исправлено.

А строчка из вашего сообщения об ошибке больше похожа на `v1.1.0` https://github.com/IATkachenko/HA-YandexWeather/blob/a5bf5bc7047b85840249fc7f3d561600238da4b4/custom_components/yandex_weather/__init__.py#L50https://github.com/IATkachenko/HA-YandexWeather/blob/a5bf5bc7047b85840249fc7f3d561600238da4b4/custom_components/yandex_weather/__init__.py#L50

`manifest.json` покажите, пожалуйста, из каталога с интеграцией.

**Comment by robulanetteam** [comment]
Все верно, видимо ошибка была связана со старой версией. Нужно разобраться с HACS. Я переустановил и ошибка ушла. Спасибо!
