### ISSUE TITLE
прокидывать код иконки в прогнозе

### ISSUE THREAD

**Issue by alexbilevskiy** [IATkachenko/HA-YandexWeather#78]
Иконку текущей погоды можно взять из `entity_picture`. Но яндекс отдает иконки в прогнозах тоже. Реально ли их прокинуть в HA?

Я впринципе могу попробовать сам, но нужен совет тогда. Посмотрел навскидку исходный код, `Forecast` это dict с фиксированными полями, то есть поле icon туда не впихнешь? Но вроде кастомные поля можно добавлять в `extra_state_attributes` у самой сущности погоды. Как смотрите на то чтобы например добавить туда `forecast_icon_0`, `forecast_icon_1`?

**Comment by IATkachenko** [comment]
Можно сделать.
У меня висит PR на большой рефакторинг апдейтера, после которого это будет существенно проще. Надо его до master'a таки дотащить :)

Вам удобнее доп атрибутами или сенсоров прикрутить?
Кстати еще можно в атрибут положить json, чтобы в шаблонах с ним работать было удобнее и обращаться к нужному элементу массива, а не к другому атрибуту/сенсору.

**Comment by alexbilevskiy** [comment]
Наверное, лучше атрибутами, чтобы не грузить ХА лишними сенсорами. Про массив в атрибуте хорошая идея.

Спасибо)

**Comment by IATkachenko** [comment]
Вот такая штука получилась:
```
{{ state_attr('weather.yandex_weather','forecast_icons') }}
{{ state_attr('weather.yandex_weather','forecast_icons')[0] }}
{{ state_attr('weather.yandex_weather','forecast_icons')[1] }}
```
![изображение](https://github.com/IATkachenko/HA-YandexWeather/assets/17473830/2939157b-1a74-4643-acce-5e19964c5805)

Релиз чуть позже выложу -- локально гоняю.

**Comment by alexbilevskiy** [comment]
То что надо! спасибо 🔥
