### ISSUE TITLE
forecast

### ISSUE THREAD

**Issue by xaxexa** [IATkachenko/HA-YandexWeather#80]
### The problem

For some reason, the "forecast" shows for 2 days (is it intended?), Both have the same day of the week, and the temperature is different
![Screenshot_20230724_113048_Home Assistant](https://github.com/IATkachenko/HA-YandexWeather/assets/17970998/cbfc5b8b-68a9-4734-b2d9-e107eadb38dc)

### What version of the integration has the issue?

3.1.0

### What version of Home Assistant Core has the issue?

2023.7.3

### What type of installation are you running?

Home Assistant Core

**Comment by alexanderznamensky** [comment]
Forecast is not available now (in my case). Is it Yandex issue?

**Comment by IATkachenko** [comment]
@xaxexa, hello.
Yandex offer forecast for two 6hours time intervals, so at 06:00 it will be for 12:00 and for 18:00. All within same day, but whit different data.

**Comment by IATkachenko** [comment]
@alexanderznamensky, could you create new issue with missed forecast? Right now all forecast data is available (in my case).
