### ISSUE TITLE
forecast is not available in `2023.8`

### ISSUE THREAD

**Issue by alexanderznamensky** [IATkachenko/HA-YandexWeather#82]
### The problem

After update to HA 2023.8.1 the forecast is disappeared.
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/805e4716-3e07-4193-82f8-dc55ede9cf14)

### What version of the integration has the issue?

3.1.0

### What version of Home Assistant Core has the issue?

2023.8.1

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```txt
nothing
```

### Additional information

It is started from  HA 2023.8.0

**Comment by IATkachenko** [comment]
Thank you! I'll check  `2023.8`.

**Comment by IATkachenko** [comment]
Ooops... https://github.com/home-assistant/core/pull/75219 
Is not breaking change at all ... https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes

Will fix it today.

**Comment by IATkachenko** [comment]
Home Assistant is not support 2 period forecasts now https://github.com/home-assistant/frontend/pull/15028/files#diff-de1db84a1734ed7fa27f246548093ebeb4d53333209a493211c80b1e0e31825eR567 / https://github.com/home-assistant/frontend/pull/15028/files#diff-de1db84a1734ed7fa27f246548093ebeb4d53333209a493211c80b1e0e31825eR616

**Comment by IATkachenko** [comment]
"исправлено" в [v3.1.1](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.1.1)

**Comment by alexanderznamensky** [comment]
Игорь, спасибо!
Правильно лия понимаю, что в UI теперь 2 периода не будет отражаться?

Странно то, что на одном сервере у меня почему-то после обновления появился прогноз в карточке, а на трех - нет.
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/65254375/5143c6ea-6f61-44c8-8748-c13c983c184f)

**Comment by IATkachenko** [comment]
@alexanderznamensky 
Я в интеграции сделал грязный хак чтобы все работало.
Правильное поведение сейчас (HA 2023.8.1 + v3.1.1 интеграции) -- карточка (и если просто на weather entity кликнуть) с прогнозом и подписями день/ночь.
Варианты следующие:
  * есть прогноз / нет подписей -- HA < 2023.8, интеграция < 3.1.1
  * не грузится интеграция -- HA < 2023.8, интеграция == 3.1.1 (уже поправил `hacs.json`)
  * нет прогноза -- HA >= 2023.8, интеграция < 3.1.1
  * есть прогноз и подписи -- HA >= 2023.8 интеграция >= 3.1.1
Ваш скриншот похож на "HA < 2023.8, интеграция < 3.1.1"
