### ISSUE TITLE
Ошибка добавления интеграции: Invalid handler specified

### ISSUE THREAD

**Issue by Sicness** [IATkachenko/HA-YandexWeather#83]
### The problem

Home Assistant Core 
HA-YandexWeather: 3.1.1

При добавлении интеграции сразу кидает ошибку: 
Ошибка
Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}

### What version of the integration has the issue?

3.1.1

### What version of Home Assistant Core has the issue?

2023.7.2

### What type of installation are you running?

Home Assistant OS

### Additional information

Пробовал нажать "загрузить повторно в HACS"

**Comment by Ujuf66** [comment]
Имею такую же проблему.
HA-YandexWeather: 3.1.1
Home Assistant 2023.7.2 Docker

**Comment by VolkovDmitriyI** [comment]
Такая же проблема 
HA-YandexWeather: 3.1.1
Home Assistant 2023.6 Docker

**Comment by IATkachenko** [comment]
Поломал обратную совместимость в #82 
Нужно или откатить интеграцию, или обновить HA до 2023.8
Сори.

**Comment by VolkovDmitriyI** [comment]
Да, обновить HA до 2023.8 решило проблему. Спасибо.

**Comment by Leon2k** [comment]
Аналогичная проблема в HA Supervized 2024.2

Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 11:43:55 (1 occurrences)
Last logged: 11:43:55

Error occurred loading flow for integration tattelecom_intercom: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
