### ISSUE TITLE
Установка интеграции

### ISSUE THREAD

**Issue by Krypt0nC0R3** [IATkachenko/HA-YandexWeather#87]
### В чем проблема?

При установке интеграции (версия 3.1.1) как из HACS, так и в ручную на странице интеграций при попытке добавить интеграцию возникает ошибка `Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}`

### При использовании какой версии интеграции возникает проблема?

3.1.1

### Какая версия Home Assistant используется?

Home Assistant 2023.3.1

### Какой способ установки Home Assistant используется?

Home Assistant Core (VENV)

### Сообщение в логе

```Error occurred loading configuration flow for integration yandex_weather: cannot import name 'ATTR_FORECAST_IS_DAYTIME' from 'homeassistant.components.weather' (/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/weather/__init__.py)```

**Comment by IATkachenko** [comment]
Минимальная версия HA для работы интеграции `2023.8`
![изображение](https://github.com/IATkachenko/HA-YandexWeather/assets/17473830/e278cc9f-ae35-4a7f-8c8f-b304560d52d5)
