### ISSUE TITLE
Почасовой прогноз яндекса

### ISSUE THREAD

**Issue by sneakythr0ws** [IATkachenko/HA-YandexWeather#88]
Привет! 
Было бы круто иметь почасовой прогноз от яндекса.

Спасибо за проделанную работу

**Comment by IATkachenko** [comment]
Как только он у них в АПИ появится -- сразу добавлю, а так они отдают только прогноз на два интервала утро/день/вечер/ночь :(

**Comment by sneakythr0ws** [comment]
@IATkachenko похоже, это зависит от тарифа
![image](https://github.com/IATkachenko/HA-YandexWeather/assets/1594945/8e92b81f-26dc-4f94-9527-03255a3ff731)
Текущая погода и `2 последующих периода`.

**Comment by IATkachenko** [comment]
Да, конечно зависит от тарифа.
Если у вас тариф за 30 или 60к в месяц -- найдите меня в TG -- попробуем добавить поддержку этих тарифов в интеграцию, что б был прогноз.
Поддержку тестового тарифа добавлять смысла нет -- он всего на месяц.
