### ISSUE TITLE
Integration does not start

### ISSUE THREAD

**Issue by m-novitsky** [IATkachenko/HA-YandexWeather#9]
Hi, API-key (YandexWeather) checked with 'postman'. It works. But in HA I've got this:

> 2022-02-04 09:45:46 ERROR (MainThread) [custom_components.yandex_weather.updater] Unexpected error fetching yandex_weather data: 'c'
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
> self.data = await self._async_update_data()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
> return await self.update_method()
> File "/config/custom_components/yandex_weather/updater.py", line 115, in update
> r["fact"][ATTR_API_WIND_BEARING] = WindDirection[
> File "/usr/local/lib/python3.9/enum.py", line 432, in __getitem__
> return cls._member_map_[name]
> KeyError: 'c'

Is there something with ATTR_API_WIND_BEARING?

**Comment by IATkachenko** [comment]
Hello.

It should go to `_missing_` of WindDirection and returns 0... Will rewrite this part...

**Comment by m-novitsky** [comment]
Yep, it looks like this:

> "fact": {
        "obs_time": 1643958000,
        "temp": -11,
        "feels_like": -14,
        "icon": "ovc",
        "condition": "overcast",
        "wind_speed": 0,
        "wind_dir": "c",
        "pressure_mm": 740,
        "pressure_pa": 986,
        "humidity": 92,
        "daytime": "d",
        "polar": false,
        "season": "winter",
        "wind_gust": 3
    },

**Comment by IATkachenko** [comment]
Thank you for report. Will fix it.

**Comment by IATkachenko** [comment]
Fixed in [v0.6.0](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v0.6.0).
