### ISSUE TITLE
не проходит ключ

### ISSUE THREAD

**Issue by Vooovan** [IATkachenko/HA-YandexWeather#95]
### В чем проблема?

при интеграции с HA не проходит ключ

Не могу получить данные. Проверьте корректность API-ключа в кабинете разработчика и убедитесь что выбран тариф 'Погода для сайта'. Может потребоваться до 30 минут, чтобы изменения настроек ключа вступили в силу на стороне Яндекса.

ключ выделен рекомендованным образом - для сайта
выделен более суток назад

### При использовании какой версии интеграции возникает проблема?

`v3.1.2`

### Какая версия Home Assistant используется?

core-2024.1.2

### Какой способ установки Home Assistant используется?

Home Assistant OS

### Самопроверка по созданию ключа

- [X] при добавлении ключа в кабинете разработчика он добавлялся как "тестовый"
- [X] тип ключа в кабинете разработчика был изменен на "погода для сайта"
- [X] после изменения типа ключа прошло не менее 20 минут
- [X] в кабинете разработчка я вижу что с запросы делаются именно с этим ключом

**Comment by IATkachenko** [comment]
Доброго дня,

Можно скрин из кабинета разработчика, на котором видно что ключ правильно добавлен?
Примерно такого вида
![изображение](https://github.com/IATkachenko/HA-YandexWeather/assets/17473830/bf2ac692-7e18-43fc-9e10-5d29e8ca2cb4)

**Comment by Vooovan** [comment]
![Uploading Снимок экрана 2024-01-22 в 03.38.49.png…]()

**Comment by Vooovan** [comment]
<img width="505" alt="Снимок экрана 2024-01-22 в 03 38 49" src="https://github.com/IATkachenko/HA-YandexWeather/assets/67726392/56c69585-271a-4c24-bb27-99169a849299">

**Comment by Vooovan** [comment]
<img width="1063" alt="Снимок экрана 2024-01-22 в 03 37 25" src="https://github.com/IATkachenko/HA-YandexWeather/assets/67726392/5f020674-5288-468f-a034-988c4c40d088">

**Comment by hamrlik** [comment]
Здравствуйте.
 У меня аналогичная проблема. При попытке подключения выскакивает сообщение об ошибке, но счётчик на сайте Яндекса при этом расходует +1 запрос.
<img width="552" alt="Monosnap Настройки – Home Assistant 2024-01-23 23-39-29" src="https://github.com/IATkachenko/HA-YandexWeather/assets/94803139/a5c5addb-259b-4f44-8c34-ad632f5b8865">
<img width="510" alt="Monosnap Яндекс Кабинет разработчика 2024-01-23 23-42-22" src="https://github.com/IATkachenko/HA-YandexWeather/assets/94803139/afb34034-6968-49bb-b3f3-b2a75a8f34b8">

**Comment by IATkachenko** [comment]
Итак, тариф: "тестовый".

А в шапке тикета пишите:
![изображение](https://github.com/IATkachenko/HA-YandexWeather/assets/17473830/6da0750d-128c-4834-aa1c-b72839ba1fe4)

измените тариф на "погода для сайта", как указано в инструкции, и все заработает.

Если нет -- переоткройте issue, будут нужны опять скрины и debug логи интеграции.
