### ISSUE TITLE
Добавить в `datetime` прогноза time зону

### ISSUE THREAD

**Issue by IATkachenko** [IATkachenko/HA-YandexWeather#98]
```
Хорошо, а что касается part_name - получать ее из datetime не очень удобно. Там по сути timestamp в таймзоне GMT, но в самой строке таймзона не указывается, например - 
2024-02-01T12:40:39.560677

Возможно туда таймзону добавить - 
2024-02-01T06:40:39+00:00
?
```

_Originally posted by @olesya108 in https://github.com/IATkachenko/HA-YandexWeather/discussions/39#discussioncomment-8331258_

Это -- строка, которую парсит UI -- если с таймзоной получится нормально жить -- лучше добавить

**Comment by Bagunda** [comment]
Очень нужен почасовой прогноз погоды или трёхчасовой.
Вообще не вижу смысла в этой интеграции без почасового прогноза

**Comment by IATkachenko** [comment]
> Очень нужен почасовой прогноз погоды или трёхчасовой. Вообще не вижу смысла в этой интеграции без почасового прогноза

Можете занести пожелание в Яндекс, как только они  начнут отдавать почасовой прогноз -- появится и у нас.

**Comment by IATkachenko** [comment]
Исправлено в [v3.2.1](https://github.com/IATkachenko/HA-YandexWeather/releases/tag/v3.2.1)
